variable "region" {}
variable "vpcName" {}
variable "tagOwner" {}
variable "clusterIdentifier" {}
variable "nodeGroup" {}
variable "desiredSize" {}
variable "maxSize" {}
variable "minSize" {}
variable "maxUnavailable" {}